### ISSUE TITLE
IndexError when I try to open it

### ISSUE THREAD

**Issue by WillMorrey96** [birogeri/kspace-explorer#4]
Hi, I've just tried to run the script and I get the following error regarding line 818: "IndexError: list index out of range" - I'm quite new to coding so I might be doing something wrong but I can't work out what it is :(

**Comment by birogeri** [comment]
Hi, have you got the file qrc.py in the same folder as kspace.py?
If not, please try dowloading [this](https://github.com/birogeri/kspace-explorer/archive/master.zip) zipped folder and extract it. This contains all of the required files.

**Comment by WillMorrey96** [comment]
Hi birogeri, yeah I unzipped the files; I couldn't load it in the way the instructions told me too becuase I get an error when I call Python (or Spyder, which I'm running Python on) via the command prompt. Instead I've opened the individual files in spyder and tried to run them, so I guess this is probably the issue instead. Do you know why it might not be loading from the command prompt?

**Comment by birogeri** [comment]
If you try to run from the command prompt then your working directory should be the one the files are extracted. This however seems like an issue with PyQt5, as the user interface (qrc.py) is imported correctly (otherwise your error would be elsewhere). Can you share your PyQt5 version? I think the minimum required is 5.7
Alternatively, please try the [dev branch](https://github.com/birogeri/kspace-explorer/archive/dev.zip), I have added some more detailed debugging messages for this problem

**Comment by shahinur-alam** [comment]
@probablyneedhelpwithMRI I had the same problem. 
Maybe you had the anaconda environment. I spent 2 days to fix this issues.

However, I changed my IDE to PyCharm with running virtual environment. The problem is gone.
